# Generated by Django 2.1.5 on 2020-10-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201020_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
